version: '3'
tasks:
  init-module:
    desc: go.mod 파일 복구 (Cross-Platform)
    cmds:
      # [Windows]
      - cmd: powershell -Command "if (-not (Test-Path generated/go.mod)) { mkdir -Force generated; cd generated; go mod init clarity/generated }"
        platforms: [ windows ]
      # [Linux/macOS]
      - cmd: mkdir -p generated && cd generated && ([ -f go.mod ] || go mod init clarity/generated)
        platforms: [ linux, darwin ]
    silent: true

  proto:
    desc: gRPC 코드 생성 및 Git 추가
    cmds:
      - buf generate
      - task: init-module
      - cd generated && go mod tidy
      - git add generated

  tidy:
    desc: Go 모듈 의존성 정리
    cmds:
      - go mod tidy

  build:
    desc: 에이전트 빌드
    deps: [proto, tidy]
    cmds:
      - go build -o bin/agent agent/main.go

  run:
    desc: 에이전트 실행
    deps: [build]
    cmds:
      - ./bin/agent
