package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"tower/graph/model"
	"tower/model/maindb"
	"tower/pkg/fnMapper"
	"tower/pkg/fnMiddleware"
	service "tower/services"
)

// RequestVerification is the resolver for the requestVerification field.
func (r *mutationResolver) RequestVerification(ctx context.Context, target string, typeArg model.VerificationType) (bool, error) {
	var vType maindb.VerificationType
	if typeArg == model.VerificationTypeEmail {
		vType = maindb.VerifyEmail
	} else {
		vType = maindb.VerifySMS
	}

	err := r.VerificationService.SendCode(ctx, target, vType)
	return err == nil, err
}

// ConfirmVerification is the resolver for the confirmVerification field.
func (r *mutationResolver) ConfirmVerification(ctx context.Context, target string, typeArg model.VerificationType, code string) (bool, error) {
	var vType maindb.VerificationType
	if typeArg == model.VerificationTypeEmail {
		vType = maindb.VerifyEmail
	} else {
		vType = maindb.VerifySMS
	}

	err := r.VerificationService.VerifyCode(ctx, target, vType, code)
	return err == nil, err
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.User, error) {
	srvInput := service.RegisterInput{
		Username:       input.Username,
		Password:       input.Password,
		Name:           input.Name,
		Email:          input.Email,
		PhoneNumber:    input.PhoneNumber,
		LandlineNumber: input.LandlineNumber,
		AgreeEmail:     input.AgreeEmail,
		AgreeSMS:       input.AgreeSms,
	}

	if input.BizInfo != nil {
		srvInput.BizInfo = &service.BusinessInput{
			BizRegNumber:  input.BizInfo.BizRegNumber,
			BizCEO:        input.BizInfo.BizCeo,
			BizType:       input.BizInfo.BizType,
			BizItem:       input.BizInfo.BizItem,
			BizZipCode:    input.BizInfo.BizZipCode,
			BizAddress1:   input.BizInfo.BizAddress1,
			BizAddress2:   *input.BizInfo.BizAddress2,
			BizLicenseURL: *input.BizInfo.BizLicenseURL,
		}
	}

	user, err := r.AuthService.Register(ctx, srvInput)
	if err != nil {
		return nil, err
	}

	return fnMapper.UserToGraphQL(user), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.Token, error) {
	accessToken, refreshToken, err := r.AuthService.Login(ctx, email, password)
	if err != nil {
		return nil, err
	}

	return fnMapper.TokenToGraphQL(accessToken, refreshToken), nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.Token, error) {
	newAccess, newRefresh, err := r.AuthService.RefreshToken(ctx, token)
	if err != nil {
		return nil, err
	}
	return fnMapper.TokenToGraphQL(newAccess, newRefresh), nil
}

// Withdraw is the resolver for the withdraw field.
func (r *mutationResolver) Withdraw(ctx context.Context) (bool, error) {
	userID, err := fnMiddleware.GetUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}

	err = r.AuthService.Withdraw(ctx, userID)
	return err == nil, err
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, _ := fnMiddleware.GetUserIDFromContext(ctx)

	user, err := r.UserService.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	return fnMapper.UserToGraphQL(user), nil
}
