package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"tower/graph/model"
	"tower/model/maindb"
	service "tower/services"
)

// RequestVerification is the resolver for the requestVerification field.
func (r *mutationResolver) RequestVerification(ctx context.Context, target string, typeArg model.VerificationType) (bool, error) {
	var vType maindb.VerificationType
	if typeArg == model.VerificationTypeEmail {
		vType = maindb.VerifyEmail
	} else {
		vType = maindb.VerifySMS
	}

	err := r.VerificationService.SendCode(ctx, target, vType)
	return err == nil, err
}

// ConfirmVerification is the resolver for the confirmVerification field.
func (r *mutationResolver) ConfirmVerification(ctx context.Context, target string, typeArg model.VerificationType, code string) (bool, error) {
	var vType maindb.VerificationType
	if typeArg == model.VerificationTypeEmail {
		vType = maindb.VerifyEmail
	} else {
		vType = maindb.VerifySMS
	}

	err := r.VerificationService.VerifyCode(ctx, target, vType, code)
	return err == nil, err
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.User, error) {
	srvInput := service.RegisterInput{
		Username:       input.Username,
		Password:       input.Password,
		Name:           input.Name,
		Email:          input.Email,
		PhoneNumber:    input.PhoneNumber,
		LandlineNumber: input.LandlineNumber,
		AgreeEmail:     input.AgreeEmail,
		AgreeSMS:       input.AgreeSms,
	}

	if input.BizInfo != nil {
		srvInput.BizInfo = &service.BusinessInput{
			BizRegNumber:  input.BizInfo.BizRegNumber,
			BizCEO:        input.BizInfo.BizCeo,
			BizType:       input.BizInfo.BizType,
			BizItem:       input.BizInfo.BizItem,
			BizZipCode:    input.BizInfo.BizZipCode,
			BizAddress1:   input.BizInfo.BizAddress1,
			BizAddress2:   *input.BizInfo.BizAddress2,
			BizLicenseURL: *input.BizInfo.BizLicenseURL,
		}
	}

	user, err := r.AuthService.Register(ctx, srvInput)
	if err != nil {
		return nil, err
	}

	resUser := &model.User{
		ID:             fmt.Sprint(user.ID),
		Username:       user.Username,
		Email:          user.Email,
		Name:           user.Name,
		PhoneNumber:    user.PhoneNumber,
		LandlineNumber: user.LandlineNumber,
		Role:           string(user.Role),
		Type:           string(user.Type),
	}

	if user.Type == maindb.TypeBusiness && user.BizRegNumber != nil {
		resUser.BizInfo = &model.BusinessInfo{
			BizRegNumber:  *user.BizRegNumber,
			BizCeo:        *user.BizCEO,
			BizType:       *user.BizType,
			BizItem:       *user.BizItem,
			BizZipCode:    *user.BizZipCode,
			BizAddress1:   *user.BizAddress1,
			BizAddress2:   user.BizAddress2,
			BizLicenseURL: user.BizLicenseURL,
		}
	}

	return resUser, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.Token, error) {
	accessToken, refreshToken, err := r.AuthService.Login(ctx, email, password)
	if err != nil {
		return nil, err
	}

	return &model.Token{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.Token, error) {
	newAccess, newRefresh, err := r.AuthService.RefreshToken(ctx, token)
	if err != nil {
		return nil, err
	}
	return &model.Token{
		AccessToken:  newAccess,
		RefreshToken: newRefresh,
	}, nil
}

func (r *mutationResolver) Withdraw(ctx context.Context) (bool, error) {
	// TODO: Context에서 현재 로그인한 UserID를 꺼내야 함 (Middleware 필요)
	// userID := ctx.Value("userID").(uint)
	// 임시로 하드코딩 (Middleware 구현 전이라)
	userID := uint(1)

	err := r.AuthService.Withdraw(ctx, userID)
	return err == nil, err
}

func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}
