package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"tower/graph/model"
	"tower/pkg/fnMapper"
)

// CreateEmailTemplate is the resolver for the createEmailTemplate field.
func (r *mutationResolver) CreateEmailTemplate(ctx context.Context, input model.CreateEmailTemplateInput) (*model.EmailTemplate, error) {
	template, err := r.EmailTemplateService.Create(ctx, input)
	if err != nil {
		return nil, err
	}
	return fnMapper.EmailTemplateToGraphQL(template), nil
}

// ModifyEmailTemplate is the resolver for the modifyEmailTemplate field.
func (r *mutationResolver) ModifyEmailTemplate(ctx context.Context, id int, input model.ModifyEmailTemplateInput) (*model.EmailTemplate, error) {
	template, err := r.EmailTemplateService.Update(ctx, id, input)
	if err != nil {
		return nil, err
	}
	return fnMapper.EmailTemplateToGraphQL(template), nil
}

// DeleteEmailTemplate is the resolver for the deleteEmailTemplate field.
func (r *mutationResolver) DeleteEmailTemplate(ctx context.Context, id int) (bool, error) {
	return r.EmailTemplateService.Delete(ctx, id)
}

// FindOneEmailTemplateByID is the resolver for the findOneEmailTemplateById field.
func (r *queryResolver) FindOneEmailTemplateByID(ctx context.Context, id int) (*model.EmailTemplate, error) {
	template, err := r.EmailTemplateService.FindById(ctx, id)
	if err != nil {
		return nil, err
	}
	return fnMapper.EmailTemplateToGraphQL(template), nil
}

// FindManyEmailTemplates is the resolver for the findManyEmailTemplates field.
func (r *queryResolver) FindManyEmailTemplates(ctx context.Context, page model.PageInput, search *model.EmailTemplateSearchInput) (*model.EmailTemplateList, error) {
	emailTemplates, total, err := r.EmailTemplateService.FindMany(ctx, page, search)
	if err != nil {
		return nil, err
	}

	return &model.EmailTemplateList{
		Total: int(total),
		Size:  page.Size,
		Page:  page.Page,
		List:  fnMapper.EmailTemplatesToGraphQL(emailTemplates),
	}, nil
}
