package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"tower/graph/model"

	"github.com/99designs/gqlgen/graphql"
)

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, file graphql.Upload, directory *string) (*model.FileInfo, error) {
	allowedMimeTypes := map[string]bool{
		"image/jpeg":      true,
		"image/png":       true,
		"application/pdf": true,
	}
	if !allowedMimeTypes[file.ContentType] {
		return nil, fmt.Errorf("❌ 허용되지 않는 파일 형식입니다: %s", file.ContentType)
	}

	dir := ""
	if directory != nil {
		dir = *directory
	}

	fileURL, err := r.FileService.UploadFile(ctx, file, dir)
	if err != nil {
		return nil, err
	}

	return &model.FileInfo{
		URL:      fileURL,
		FileName: file.Filename,
	}, nil
}
