package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"tower/graph/model"
	"tower/pkg/fnMapper"
)

// CreateInquiry is the resolver for the createInquiry field.
func (r *mutationResolver) CreateInquiry(ctx context.Context, input model.CreateInquiryInput) (*model.Inquiry, error) {
	inquiry, err := r.InquiryService.Create(ctx, input)
	if err != nil {
		return nil, err
	}
	return fnMapper.InquiryToGraphQL(inquiry), nil
}

// ModifyInquiry is the resolver for the modifyInquiry field.
func (r *mutationResolver) ModifyInquiry(ctx context.Context, id int, input model.ModifyInquiryInput, password *string) (*model.Inquiry, error) {
	inquiry, err := r.InquiryService.Modify(ctx, id, input, password)
	if err != nil {
		return nil, err
	}
	return fnMapper.InquiryToGraphQL(inquiry), nil
}

// DeleteInquiry is the resolver for the deleteInquiry field.
func (r *mutationResolver) DeleteInquiry(ctx context.Context, id int, password *string) (bool, error) {
	err := r.InquiryService.Delete(ctx, id, password)
	if err != nil {
		return false, err
	}
	return true, nil
}

// AnswerInquiry is the resolver for the answerInquiry field.
func (r *mutationResolver) AnswerInquiry(ctx context.Context, id int, input model.AnswerInquiryInput) (*model.Inquiry, error) {
	inquiry, err := r.InquiryService.Answer(ctx, id, input)
	if err != nil {
		return nil, err
	}
	return fnMapper.InquiryToGraphQL(inquiry), nil
}

// FindOneInquiryByID is the resolver for the findOneInquiryById field.
func (r *queryResolver) FindOneInquiryByID(ctx context.Context, id int, password *string) (*model.Inquiry, error) {
	inquiry, err := r.InquiryService.FindOneById(ctx, id, password)
	if err != nil {
		return nil, err
	}
	return fnMapper.InquiryToGraphQL(inquiry), nil
}

// FindManyPublicInquiries is the resolver for the findManyPublicInquiries field.
func (r *queryResolver) FindManyPublicInquiries(ctx context.Context, page model.PageInput, search *model.InquirySearchInput) (*model.InquiryList, error) {
	inquiries, total, err := r.InquiryService.FindManyPublic(ctx, page, search)
	if err != nil {
		return nil, err
	}

	return &model.InquiryList{
		Total: int(total),
		Size:  page.Size,
		Page:  page.Page,
		List:  fnMapper.InquiriesToPublicGraphQL(inquiries),
	}, nil
}

// FindManyMyInquiries is the resolver for the findManyMyInquiries field.
func (r *queryResolver) FindManyMyInquiries(ctx context.Context, page model.PageInput) (*model.InquiryList, error) {
	inquiries, total, err := r.InquiryService.FindManyMyInquiries(ctx, page)
	if err != nil {
		return nil, err
	}

	return &model.InquiryList{
		Total: int(total),
		Size:  page.Size,
		Page:  page.Page,
		List:  fnMapper.InquiriesToGraphQL(inquiries),
	}, nil
}

// FindManyInquiriesForAdmin is the resolver for the findManyInquiriesForAdmin field.
func (r *queryResolver) FindManyInquiriesForAdmin(ctx context.Context, page model.PageInput, search *model.InquirySearchInput) (*model.InquiryList, error) {
	inquiries, total, err := r.InquiryService.FindManyForAdmin(ctx, page, search)
	if err != nil {
		return nil, err
	}

	return &model.InquiryList{
		Total: int(total),
		Size:  page.Size,
		Page:  page.Page,
		List:  fnMapper.InquiriesToGraphQL(inquiries),
	}, nil
}
