package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"strconv"
	"tower/graph/model"
	"tower/mapper"
	"tower/pkg/fnError"
)

// ModifyUser is the resolver for the modifyUser field.
func (r *mutationResolver) ModifyUser(ctx context.Context, input model.ModifyUserInput) (*model.User, error) {
	updatedUser, err := r.UserService.Modify(ctx, input)
	if err != nil {
		return nil, err
	}

	return mapper.UserToGraphQL(updatedUser), nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (bool, error) {
	return r.UserService.ChangePassword(ctx, input)
}

// ModifyUserForAdmin is the resolver for the modifyUserForAdmin field.
func (r *mutationResolver) ModifyUserForAdmin(ctx context.Context, id string, input model.ModifyUserForAdminInput) (*model.User, error) {
	parsedID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fnError.NewBadRequest("유효하지 않은 사용자 ID입니다.")
	}

	updatedUser, err := r.UserService.ModifyUserForAdmin(ctx, uint(parsedID), input)
	if err != nil {
		return nil, err
	}

	return mapper.UserToGraphQL(updatedUser), nil
}

// CheckPassword is the resolver for the checkPassword field.
func (r *queryResolver) CheckPassword(ctx context.Context, password string) (bool, error) {
	return r.UserService.CheckPassword(ctx, password)
}

// FindManyUserForAdmin is the resolver for the findManyUserForAdmin field.
func (r *queryResolver) FindManyUserForAdmin(ctx context.Context, page model.PageInput, search *model.UserSearchInput) (*model.UserList, error) {
	users, total, err := r.UserService.FindManyUserForAdmin(ctx, page, search)
	if err != nil {
		return nil, err
	}

	return &model.UserList{
		Total: int(total),
		Size:  page.Size,
		Page:  page.Page,
		List:  mapper.UsersToGraphQL(users),
	}, nil
}

// FindOneUserForAdmin is the resolver for the findOneUserForAdmin field.
func (r *queryResolver) FindOneUserForAdmin(ctx context.Context, id string) (*model.User, error) {
	parsedID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fnError.NewBadRequest("유효하지 않은 사용자 ID 형식입니다.")
	}

	user, err := r.UserService.FindOneUserForAdmin(ctx, uint(parsedID))
	if err != nil {
		return nil, err
	}

	return mapper.UserToGraphQL(user), nil
}
