// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type BusinessInfo struct {
	BizRegNumber  string  `json:"bizRegNumber"`
	BizCeo        string  `json:"bizCEO"`
	BizType       string  `json:"bizType"`
	BizItem       string  `json:"bizItem"`
	BizZipCode    string  `json:"bizZipCode"`
	BizAddress1   string  `json:"bizAddress1"`
	BizAddress2   *string `json:"bizAddress2,omitempty"`
	BizLicenseURL *string `json:"bizLicenseURL,omitempty"`
}

type BusinessInput struct {
	BizRegNumber  string  `json:"bizRegNumber"`
	BizCeo        string  `json:"bizCEO"`
	BizType       string  `json:"bizType"`
	BizItem       string  `json:"bizItem"`
	BizZipCode    string  `json:"bizZipCode"`
	BizAddress1   string  `json:"bizAddress1"`
	BizAddress2   *string `json:"bizAddress2,omitempty"`
	BizLicenseURL *string `json:"bizLicenseURL,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Username       string         `json:"username"`
	Password       string         `json:"password"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	PhoneNumber    string         `json:"phoneNumber"`
	LandlineNumber *string        `json:"landlineNumber,omitempty"`
	AgreeEmail     bool           `json:"agreeEmail"`
	AgreeSms       bool           `json:"agreeSMS"`
	BizInfo        *BusinessInput `json:"bizInfo,omitempty"`
}

type Token struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type User struct {
	ID             string        `json:"id"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
	Username       string        `json:"username"`
	Email          string        `json:"email"`
	Name           string        `json:"name"`
	PhoneNumber    string        `json:"phoneNumber"`
	LandlineNumber *string       `json:"landlineNumber,omitempty"`
	Role           UserRole      `json:"role"`
	Type           UserType      `json:"type"`
	Status         UserStatus    `json:"status"`
	AgreeEmail     bool          `json:"agreeEmail"`
	AgreeSms       bool          `json:"agreeSMS"`
	BizInfo        *BusinessInfo `json:"bizInfo,omitempty"`
}

type UserRole string

const (
	UserRoleUser  UserRole = "USER"
	UserRoleAdmin UserRole = "ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleUser,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleUser, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
	UserStatusWithdrawn UserStatus = "WITHDRAWN"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusSuspended,
	UserStatusWithdrawn,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusSuspended, UserStatusWithdrawn:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserType string

const (
	UserTypePersonal UserType = "PERSONAL"
	UserTypeBusiness UserType = "BUSINESS"
)

var AllUserType = []UserType{
	UserTypePersonal,
	UserTypeBusiness,
}

func (e UserType) IsValid() bool {
	switch e {
	case UserTypePersonal, UserTypeBusiness:
		return true
	}
	return false
}

func (e UserType) String() string {
	return string(e)
}

func (e *UserType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserType", str)
	}
	return nil
}

func (e UserType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VerificationType string

const (
	VerificationTypeEmail VerificationType = "EMAIL"
	VerificationTypeSms   VerificationType = "SMS"
)

var AllVerificationType = []VerificationType{
	VerificationTypeEmail,
	VerificationTypeSms,
}

func (e VerificationType) IsValid() bool {
	switch e {
	case VerificationTypeEmail, VerificationTypeSms:
		return true
	}
	return false
}

func (e VerificationType) String() string {
	return string(e)
}

func (e *VerificationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VerificationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VerificationType", str)
	}
	return nil
}

func (e VerificationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VerificationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VerificationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
